development:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  minerthreads: 1
  datadir: /tmp/embark
  mine_when_needed: true
  gas_limit: 2500000
  console: false
  account:
    init: true
    password: config/password
staging:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 0
  console: true
  account:
    init: false
    address: 
